import { cp, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const upstreamEntry = require.resolve("@libmedia/avplayer");
const upstreamRoot = path.resolve(path.dirname(upstreamEntry), "../..");
const upstream = JSON.parse(await readFile(path.join(upstreamRoot, "package.json"), "utf8"));
const expectedVersion = "1.3.1";
if (upstream.version !== expectedVersion) {
  throw new Error(`Bundled player loader supports @libmedia/avplayer ${expectedVersion}; found ${upstream.version}. Review the upstream chunk loaders before updating.`);
}

// libmedia creates its own workers by serializing a webpack bootstrap. Both
// bootstraps need absolute URLs: the browser cannot resolve sibling chunks
// relative to a blob URL. Keep the original distribution available separately.
const mainChunkLoader = "var o=s.p+s.u(t),";
const workerChunkLoader = "var url = __webpack_require__.p + __webpack_require__.u(chunkId);";
const umdDir = path.join(upstreamRoot, "dist/umd");
const playerSource = await readFile(path.join(umdDir, "avplayer.js"), "utf8");
for (const marker of [mainChunkLoader, workerChunkLoader]) {
  if (playerSource.split(marker).length !== 2) {
    throw new Error(`Expected exactly one upstream chunk loader marker: ${marker}`);
  }
}

const chunks = {};
const entries = (await readdir(umdDir)).sort();
for (const file of entries) {
  const match = /^(\d+)\.avplayer\.js$/.exec(file);
  if (match) chunks[match[1]] = await readFile(path.join(umdDir, file), "utf8");
  else if (file.endsWith(".js") && file !== "avplayer.js") {
    throw new Error(`Unexpected upstream player asset ${file}. Review the bundle generator.`);
  }
}
if (!Object.keys(chunks).length) throw new Error("The upstream player has no worker chunks.");

const wasmFiles = [
  "h264-simd.wasm",
  "hevc-simd.wasm",
  "aac-simd.wasm",
  "resample-simd.wasm",
  "stretchpitch-simd.wasm",
];
const wasm = {};
for (const file of wasmFiles) {
  const bytes = await readFile(path.join(packageRoot, "wasm", file));
  if (!WebAssembly.validate(bytes)) throw new Error(`Invalid bundled WASM resource: ${file}`);
  wasm[file] = bytes.toString("base64");
}

const generated = `// Generated by scripts/build-assets.mjs from libmedia ${expectedVersion}.
// libmedia assets are LGPL-3.0-or-later. See COPYING.LGPLv3 and wasm/SOURCES.md.
// Only chunk URL resolution is adapted; the raw vendor distribution is included.
const playerSource = ${JSON.stringify(playerSource)};
const chunkSources = ${JSON.stringify(chunks)};
const wasmSources = ${JSON.stringify(wasm)};
let cachedAssets;

/** Create page-lifetime URLs only when a browser actually needs the player. */
export function getBundledAssets() {
  if (typeof window === "undefined") throw new Error("hevc-player runs in the browser.");
  if (cachedAssets) return cachedAssets;

  const createdUrls = [];
  const createUrl = (content, type) => {
    const url = URL.createObjectURL(new Blob([content], { type }));
    createdUrls.push(url);
    return url;
  };
  try {
    const chunkUrls = {};
    for (const [id, source] of Object.entries(chunkSources)) {
      chunkUrls[id] = createUrl(source, "text/javascript");
    }
    const chunkMap = JSON.stringify(chunkUrls);
    // The worker loader is inside a single-quoted JavaScript source string.
    // Escape that extra string layer without altering the source of chunks.
    const workerLookup = JSON.stringify("var url = " + chunkMap + "[chunkId];")
      .slice(1, -1).replace(/'/g, "\\\\'");
    const source = playerSource
      .replace(${JSON.stringify(mainChunkLoader)}, "var o=" + chunkMap + "[t],")
      .replace(${JSON.stringify(workerChunkLoader)}, workerLookup);
    const scriptUrl = createUrl(source, "text/javascript");
    const wasmUrls = {};
    for (const [name, encoded] of Object.entries(wasmSources)) {
      const binary = atob(encoded);
      const bytes = new Uint8Array(binary.length);
      for (let index = 0; index < binary.length; index++) bytes[index] = binary.charCodeAt(index);
      wasmUrls[name] = createUrl(bytes, "application/wasm");
    }
    // Workers can request additional chunks after individual players are
    // destroyed. Reuse these URLs until the document itself is unloaded.
    cachedAssets = { scriptUrl, wasmUrls };
    return cachedAssets;
  } catch (error) {
    for (const url of createdUrls) URL.revokeObjectURL(url);
    throw error;
  }
}
`;

await mkdir(path.join(packageRoot, "dist"), { recursive: true });
await mkdir(path.join(packageRoot, "vendor"), { recursive: true });
await cp(umdDir, path.join(packageRoot, "vendor"), { recursive: true });
await cp(path.join(upstreamRoot, "COPYING.LGPLv3"), path.join(packageRoot, "vendor/COPYING.LGPLv3"));
await writeFile(path.join(packageRoot, "dist/bundled-assets.js"), generated);
await writeFile(path.join(packageRoot, "dist/bundled-assets.d.ts"), `/** Assets included with the package; URLs are created lazily in the browser. */
export declare function getBundledAssets(): {
  scriptUrl: string;
  wasmUrls: Record<string, string>;
};
`);
console.log(`Bundled libmedia ${expectedVersion}: ${Object.keys(chunks).length} player chunks and ${wasmFiles.length} WASM resources.`);
